version: "3"
services:
  node:
    container_name: emails-app
    build:
      context: ./backend
      dockerfile: Dockerfile.dev

    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db

    networks:
      - backend-network

  db:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: maillingsapp
      MONGO_INITDB_ROOT_USERNAME: krystian91
      MONGO_INITDB_ROOT_PASSWORD: pr4KQCtzqKbh0rNT
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongo_db:/data/db

    networks:
      - backend-network

networks:
  backend-network:

volumes:
  app:
  mongo_db:
