
FROM node:latest

RUN echo "running dev mode"

ADD . ./backend
WORKDIR /backend

RUN npm install -g typescript --silent
RUN npm i -g nodemon --silent
RUN npm install --legacy-peer-deps --silent

RUN rm -rf .next
RUN npm run build

ENTRYPOINT [ "npm", "run", "dev" ] 